#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
frases.py - Frases Yota Modulo
Es el segundo modulo echo a mano :p
Copyright 2016, Santos D. Dominges
"""
import random

def fact_core(m5, input):
  """
  Aqui puse muchas frases muy sabias u.u ;)
  """

  quotes = [
    "El que busca un amigo sin defectos se queda sin amigos. « Proverbio turco",
    "Lo pasado ha huido, lo que esperas esta ausente, pero el presente es tuyo. « Proverbio arabe",
    "La gente se arregla todos los dias el cabello. ¿Por que no el corazon? « Proverbio chino",
    "Si lo que vas a decir no es mas bello que el silencio: no lo digas. « Proverbio arabe",
    "La primera vez que me engañes, sera culpa tuya; la segunda vez, la culpa sera mia. « Proverbio arabe",
    "Si te caes siete veces, levantate ocho. « Proverbio arabe",
    "La paciencia es un arbol de raiz amarga pero de frutos muy dulces. «Proverbio persa",
    "Un libro abierto es un cerebro que habla; cerrado un amigo que espera; olvidado, un alma que perdona; destruido, un  corazon que llora. « Proverbio hindu",
    "Quien no comprende una mirada tampoco comprendera una larga explicacion. « Proverbio arabe",
    "Las grandes almas tienen voluntades; las debiles tan solo deseos. « Proverbio chino",
    "Antes de poner en duda el buen juicio de tu mujer, fijate con quien se ha casado ella. « Proverbio egipcio",
    "¡Caer esta permitido. Levantarse es obligatorio!. « Proverbio ruso",
    "Estaba furioso de no tener zapatos; entonces encontre a un hombre que no tenia pies, y me senti contento de mi mismo. « Proverbio",
    "Es una locura amar, a menos de que se ame con locura. « Proverbio Latino",
    "Las lagrimas derramadas son amargas, pero mas amargas son las que no se derraman. « Proverbio irlandes",
    "Cuando te inunde una enorme alegria, no prometas nada a nadie. Cuando te domine un gran enojo, no contestes ninguna carta. « Proverbio chino",
    "Castiga a los que tienen envidia haciendoles bien. « Proverbio arabe",
    "Es mejor viajar lleno de esperanza que llegar. « Proverbio japones",
    "Con una mentira suele irse muy lejos, pero sin esperanzas de volver. « Proverbio judio",
    "Cuando apuntas con el dedo, recuerda que tres dedos te señalan a ti. « Proverbio ingles",
    "Mientras el timido reflexiona, el valiente va, triunfa y vuelve. « Proverbio griego",
    "El amor hace pasar el tiempo; el tiempo hace pasar el amor. « Proverbio italiano",
    "Si quieres que algo se haga, encargaselo a una persona ocupada. « Proverbio chino",
    "Del escuchar procede la sabiduria, y del hablar el arrepentimiento. « Proverbio italiano",
    "Al perro que tiene dinero se le llama señor perro. « Proverbio arabe",
    "Una vez terminado el juego el rey y el peon vuelven a la misma caja. « Proverbio italiano",
    "Es mas facil variar el curso de un rio que el caracter de un hombre. « Proverbio chino",
    "El que teme sufrir ya sufre el temor. « Proverbio chino",
    "No hay arbol que el viento no haya sacudido. « Proverbio hindu",
    "La crueldad es la fuerza de los cobardes. « Proverbio arabe",
    "La mujer llora antes del matrimonio, el hombre despues. « Proverbio polaco",
    "¿Que sentido tiene correr cuando estamos en la carretera equivocada? « Proverbio aleman",
    "Los ojos no sirven de nada a un cerebro ciego. « Proverbio arabe",
    "Pideles consejos a los viejos y a los jovenes, pero sigue tu propio sentido comun. « Proverbio arabe",
    "No hables mal del puente hasta haber cruzado el rio. « Proverbio",
    "Cuando bebas agua, recuerda la fuente. « Proverbio chino",
    "El tiempo que pasa uno riendo es tiempo que pasa con los dioses. « Proverbio japones",
    "Jamas se desvia uno tan lejos como cuando cree conocer el camino. « Proverbio chino",
    "A quien teme preguntar, le averguenza aprender. « Proverbio danes",
    "Si todos tirasemos en la misma direccion, el mundo volcaria. « Proverbio judio",
    "Reza, pero no dejes de remar hacia la orilla. « Proverbio ruso",
    "Añorar el pasado es correr tras el viento. « Proverbio ruso",
    "La union en el rebaño obliga al leon a acostarse con hambre. « Proverbio africano",
    "Nadie prueba la profundidad del rio con ambos pies. « Proverbio",
    "Si quieres miel no des puntapies sobre la colmena. « Proverbio americano",
    "Las palabras son enanos, los ejemplos son gigantes. « Proverbio suizo",
    "La mitad de la alegria reside en hablar de ella. « Proverbio persa",
    "¿Que ve el ciego, aunque se le ponga una lampara en la mano? « Proverbio hindu",
    "Antes de iniciar la labor de cambiar el mundo, da tres vueltas por tu propia casa. « Proverbio chino",
    "Si tu mal tiene remedio ¿por que te quejas?. Si no lo tiene ¿por que te quejas?. « Proverbio oriental",
    "Si no quieres que se sepa, no lo hagas. « Proverbio chino",
    "Libros, caminos y dias dan al hombre sabiduria. « Proverbio arabe",
    "Un tropezon puede prevenir una caida. « Proverbio ingles",
    "El que no da un oficio a su hijo, le enseña a ser ladron. « Proverbio turco",
    "No puede impedirse el viento. Pero pueden construirse molinos. « Proverbio Holandes",
    "Ningun amigo como un hermano; ningun enemigo como un hermano. « Proverbio indio",
    "Cuando el carro se haya roto muchos os diran por donde no se debia pasar. « Proverbio turco",
    "Aunque tu mujer haya cometido cien faltas no la golpees ni con una flor. « Proverbio indio",
    "Todos los hombres estamos hechos del mismo barro, pero no del mismo molde. « Proverbio mexicano",
    "La sabiduria viene de escuchar; de hablar, el arrepentimiento. « Proverbio italiano",
    "La respuesta mas rapida es la accion. « Proverbio americano",
    "Excava el pozo antes de que tengas sed. . « Proverbio chino",
    "Un pajaro no canta porque tenga una respuesta. Canta porque tiene una cancion. « Proverbio chino",
    "Un libro es como un jardin que se lleva en el bolsillo. « Proverbio arabe",
    "La escalera ha de barrerse empezando por arriba. « Proverbio rumano",
    "El corazon en paz ve una fiesta en todas las aldeas. « Proverbio hindu",
    "La lengua resiste porque es blanda; los dientes ceden porque son duros. « Proverbio chino",
    "El que se pone de puntillas no puede sostenerse derecho. « Proverbio chino",
    "Todos los hombres son sabios; unos antes, los otros, despues. « Proverbio chino",
    "El que nada duda, nada sabe. « Proverbio griego",
    "Oir es precioso para el que escucha. « Proverbio egipcio",
    "Cada paso que da el zorro le acerca mas a la peleteria. « Proverbio chino",
    "La tinta mas pobre de color vale mas que la mejor memoria. « Proverbio chino",
    "Quien no sabe bailar dice que los tambores no valen para nada. « Proverbio danes",
    "Mas confio en el trabajo que en la suerte. « Proverbio latino",
    "Dos perros pueden matar a un leon. « Proverbio hebreo",
    "Vale mas ser cobarde un minuto que muerto el resto de la vida. « Proverbio holandes",
    "Cuando los elefantes luchan, la hierba es la que sufre. « Proverbio africano",
    "El hombre no puede saltar fuera de su sombra. « Proverbio arabe",
    "Contra mas grande la cabeza, mas grande la jaqueca. « Proverbio",
    "El hombre que hace su fortuna en un año deberia ser ahorcado doce meses antes. « Proverbio ruso",
    "Todos los rios van al mar, pero el mar no se desborda. «Proverbio chino",
    "Al comprar una casa, piensa en el vecino que adquiriras con ella. « Proverbio",
    "Mira a las estrellas, pero no te olvides de encender la lumbre en el hogar. « Proverbio aleman",
    "La sabiduria inutil solo se diferencia de la tonteria en que da mucho mas trabajo. « Proverbio sueco",
    "Mas vale una cabra que da leche que una vaca esteril. « Proverbio estoniano",
    "Cuando tres marchan juntos, tiene que haber uno que mande. « Proverbio manchu",
    "El que quiera ser lider debe ser puente. « Proverbio gales",
    "El caballo conoce por la brida al que lo guia. « Proverbio turco",
    "Repara tu trineo en el verano, y tu carreta en el invierno. « Proverbio armenio",
    "Solo en la actividad desearas vivir cien años. « Proverbio japones",
    "Para aprender a rezar no hay como viajar por mar. « Proverbio ingles"
    "Solo se vive cuando se ama(Claude-Adrien Helvetius)",
    "Me gusta estar feliz. Es mas divertido(Maria)", 
    "Nunca se sabe hasta donde pueden llegar en el espacio y en el tiempo las consecuencias de un acto(Juan)",
    "Lo que convierte la vida en una bendicion no es hacer lo que nos gusta, sino que nos guste lo que hacemos(GOETHE)",
    "Empieza tu dia con una sonrisa(Mafalda)",
    "Me gustan los dias; me gustan todos los dias(Carmen, 7 años)", 
    "No hay que tener miedo. Si tienes miedo no das un paso adelante(Maria, 10 años)",
    "La alegria es, ante todo, fomento de la salud(Joseph Addison)",
    "La mirada es un puente entre dos almas(Juan)",
    "Cuando se hace el bien es preciso hacerlo alegremente(Talmud)",
    "Cada hombre debe inventar su propio camino(Jean Paul Sartre)",
    "Tu vida es lo que has dado(Giorgios Seferis)",
    "Justicia es la constante y perpetua voluntad de dar a cada uno lo suyo (Ulpiano) (Enviada por Marta)",
    "El perdon no cambia el pasado pero si el futuro(desconozco el autor)",
    "Todo cambia, todo se mueve, aunque a veces no nos demos cuenta: nadie ha visto crecer la hierba(Juan)",
    "El cerebro humano sigue evolucionando durante la edad adulta... cada vez que aprendemos algo se modifican los circuitos cerebrales y se tejen nuevas mallas en la red de las neuronas. .. Es posible entrenar la capacidad para ser felices(Stefan Klein)",
    "Las personas felices son mas creativas... Resuelven los problemas mejor y en menos tiempo... La alegria mejora las facultades mentales       (Stefan Klein)", 
    "La felicidad es dos cosas al mismo tiempo: meta vital y ruta hacia una vida mejor(Stefan Klein)", 
    "Se puede aprender a ser feliz(Stefan Klein)",
    "Una vida feliz nunca es un regalo del destino. Hay que hacer algo para conseguirla(Stefan Klein)",
    "El pais mas poderoso del mundo y el pais mas feliz del mundo tienen nombres diferentes(Juan)",
    "Al observador atento, la vida cotidiana le ofrece una infinidad de encantos que pasan desapercibidos para los demas(Stefan Klein)",
    "El hombre mas rico del mundo y el hombre mas feliz del mundo no se conocen personalmente(Juan)",
    "Se puede comprar el sexo pero no el amor(Juan)",
    "Para conocer a la gente hay que ir a su casa(Goethe)",
    "La gente se arregla todos los dias el cabello. ¿Por que no el corazon?(Proverbio chino*)",
    "No basta compartir las ideas con el projimo. Se ha de compartir la vida(Tagore)",
    "Dios no nos ha dado palabras en conserva para que las custodiemos, sino palabras vivas para alimentarnos y alimentar a los otros(Charles Peguy)",
    "Desgraciado quien no haya amado mas que cuerpos, formas y apariencias. La muerte le arrebatara todo. Procurad amar las almas y un dia las volvereis a encontrar(Victor Hugo)",
    "Una mirada transparente muestra la luz del corazon(Juan)",
    "Es un gran privilegio haber vivido una vida dificil(INDIRA GANDHI)",
    "Practica tu propia religion. Si quieres, beneficiate tambien de las enseñanzas de otras religiones. Esto te ayudara a ser un buen ser humano, que es el unico camino para ser feliz(Creo que esta frase la dijo un monje del Tibet, cuyo nombre ignoro)",
    "Dos cosas definen a un hombre: su mirada y su corazon(P. Willot)",
    "Dios provee a cada pajaro con alimento, pero no se lo hecha en el nido(George Herbert)",
    "Disfruta de las pequeñas cosas, porque puede que un dia vuelvas la vista a tras y te des cuenta de que eran las cosas grandes(Robert Brault)",
    "El sabio cuida principalmente de la raiz(Confucio)",
    "No es sabio el que sabe muchas cosas, sino el que sabe cosas utiles(Esquilo)", 
    "Solo se que no se nada(Socrates)",
    "La mayor sabiduria que existe es conocerse a si mismo(Galileo)",
    "Sufrir y llorar significa vivir(Dostoiesvski)",
    "Procura llevar las riendas de tu vida, pero, cuando sea la vida la que te arrastre, procura encajar los golpes(Juan)",
    "Encuentra la felicidad en el trabajo o nunca seras feliz(Cristobal Colon)",
    "El trabajo es, a menudo, el padre del placer(Voltaire)",
    "Cuando tengais un momento fastidiado, haced de vuestro muro un peldaño(enviada por Alicia Bello, que se la escucho a su profe de arte)",
    "El dia nunca le parece largo al que trabaja(Seneca)",
    "Cuando un lobo se empeña en tener razon, pobres corderos(Esopo)",
    "Fuimos engendrados en un relampago de gozo. ¿Por que hemos de ser tristes?(Luis L. Franco)",
    "Vida sin fiestas es como un largo camino sin posadas(Democrito)",
    "Una pintura es un poema sin palabras(Horacio)",
    "La musica es amor en busca de palabras(Sidney Lanier)",
    "Sin musica la vida seria un error(Nietzsche)",
    "El mejor cosmetico para la belleza es la felicidad. (Condesa de Blessington)",
    "La contemplacion de la naturaleza me ha convencido de que nada de lo que podemos imaginar es increible(Plinio el Viejo)",
    "Mas enseña la necesidad que la universidad(Desconozco el autor)",
    "Engarza en oro las alas del pajaro y nunca mas volara al cielo(Tagore)", 
    "Las lagrimas son la sangre del alma(San Agustin )", 
    "La pluma es lengua del alma(Miguel de Cervantes)",
    "Si muero, no morire del todo(Salvador Dali)",
    "El tiempo no se mide con el reloj, sino con el aburrimiento(Sofocleto)",
    "Opino que lo que se llama belleza, reside unicamente en la sonrisa. (Tolstoi)",
    "La vida de los muertos esta en la memoria de los vivos(Ciceron)",
    "Quien conserva la facultad de ver la belleza no envejece(Franz Kafka)",
    "Cuando llegue mi hora de morir, morire; pero sabre dar la vida como hombre que no le duele devolver el prestamo que le han hecho(Epicteto)",
    "¿No sabes que la fuente de todas las miserias, para el hombre, no es la muerte sino el miedo a la muerte? (Epicteto)",
    "Aprende a vivir y sabras morir bien(Confucio)",
    "Asi como una jornada bien empleada produce un dulce sueño, asi una vida bien usada causa una dulce muerte(Leonardo da Vinci)",
    "Si un partido politico se atribuye el merito de la lluvia, no debe extrañarse que sus adversarios le hagan culpable de la sequia.(Charlotte Morrow)",
    "La poesia es una aventura hacia el absoluto(Pedro Salinas)",
    "Sobre la Tierra, antes que la escritura y la imprenta, existio la poesia(Pablo Neruda)",
    "No hay en la tierra contento que se iguale a alcanzar la libertad perdida(Miguel de Cervantes)", 
    "El arte de vivir consiste menos en eliminar nuestros problemas que en aprender a vivir con ellos(Baruch)",
    "La posesion de medios de produccion maravillosos no ha aportado la libertad, sino la inquietud y el hambre(Einstein)",
    "Que desaparezca entre vosotros toda agresividad, rencor, ira, indignacion, injurias y toda suerte de maldad .... haced del amor la norma de vuestra vida ... Poned atencion en comportaros no como necios, sino como sabios, aprovechando el momento presente ... Llenaos del Espiritu, y recitad entre vosotros salmos, himnos y canticos inspirados. Cantad y tocad para el Señor con todo vuestro corazon, y dad continuamente gracias a Dios Padre por todas las cosas ... Guardaos mutuamente respeto ...(La Biblia. Carta a los Efesios)",
    "Una mentira nunca vive hasta hacerse vieja(Sofocles*)",
    "La filosofia no es mas que el sentido comun en traje de etiqueta(Oliver S. Braston)",
    "Todo hombre genial es en cierta medida hombre, mujer y niño al mismo tiempo(Henry Havelock Ellis)",
    "Para saber hablar es preciso saber escuchar(Plutarco)",
    "La mirada es la puerta principal de la catedral de la comunicacion(Juan)", 
    "El que callar no puede, hablar no sabe(Seneca)",
    "Se secan las lagrimas mezclandolas(Filippo Pananti)",
    "Al que fortuna le viste, fortuna le desnuda(Proverbio arabe)",
    "Si quieres que te oigan en el corazon, habla desde el corazon(Juan)",
    "No existe en el mundo nada mas poderoso que una idea a la que le ha llegado su tiempo(Victo Hugo)",
    "La inteligencia embellece a la gente(Oriana Fallaci)",
    "Si el mundo fuera obvio, el arte no existiria. El arte nos ayuda a penetrar la opacidad del mundo(Albert Camus)",
    "El arte mas dificil y mas importante es el arte de vivir feliz(Juan)", 
    "La sintesis espiritual de un pais es su arte(angel Ganivet)", 
    "El arte tiene don de lenguas(James Joyce)",
    "Cuatro caracteristicas corresponden al juez: escuchar cortesmente, responder sabiamente, ponderar prudentemente y decidir imparcialmente(Socrates)", 
    "Consuelate de soportar las injusticias, la verdadera desgracia consiste en cometerlas(Pitagoras)", 
    "Si un genio nace pobre, seguira siendo un genio, pero lo mas probable es que la humanidad no se entere(Juan)",
    "Hay muchos genios cavando en las huertas y muchos mediocres gobernando naciones(Juan)", 
    "El genio que necesita cavar para comer tiene escasos medios para dejar constancia de su genialidad (Juan)",
    "La mujer es el rayo de la luz divina(Djalai Al-Din Rumi)",
    "Los dioses no han hecho mas que dos cosas perfectas: la mujer y la rosa(Solon)",
    "Tu risa, mujer, es la musica de la fuente de la vida(Tagore)",
    "Los ojos son el punto donde se mezclan alma y cuerpo(Friedrich Hebbel)",
    "La mirada, el beso y la caricia son las llaves del corazon(Juan)",
    "Cada vez que un hombre rie, añade un par de dias a su vida(Curzio Malaparte)",
    "Un politico piensa en las proximas elecciones; un estadista, en la proxima generacion(James F. Clarke)",
    "La risa es la distancia mas corta entre dos personas(Victor Borge       "
    "Si eres sabio, rie(Marcial)",
    "Hay quien cruza el bosque y no ve leña para el fuego(Leon Tolstoi)", 
    "El infinito tiene su voz: es el silencio(Gabriel Alomar)",
    "El silencio es un amigo que jamas traiciona(Confucio)",
    "La palabra es plata; el silencio, oro(Probervio)",
    "Las utopias no son a menuno otra cosa que verdades prematuras(Alphonse de Lamartine)",
    "El que hace reir a sus compañeros merece el paraiso(Mahoma)",
    "Los jovenes de hoy aman el lujo, tienen manias y desprecian la autoridad. Responden a sus padres, cruzan las piernas y tiranizan a sus maestros(Socrates, filosofro griego, 470-399 antes de Cristo)",
    "Si haces algo, hazlo(Plauto)",
    "No hagas lo que te guste hacer ahora, sino lo que te guste luego haber hecho(Jackes Deval)",
    "Cuando se necesitan brazos, el socorro de las palabras no sirve de nada(Esopo)",
    "El genio es un rayo cuyo trueno se prolonga durante siglos(Knut Hamsum)",
    "Gobierna mejor quien gobierna menos(Lao Tse)",
    "El sol acepta pasar por pequeñas ventanas(Frederuick Van Eden)",
    "Comienza el dia con una sonrisa, veras lo divertido que es ir desentonando con el resto de la humanidad",
    "Las drogas producen amnesia y algo mas que no me acuerdo.", 
    "La inteligencia me persigue pero yo soy mas rapido.",
    "Bienaventurados los borrachos porque ellos veran a Dios 2 veces.",
    "El que es capaz de sonreir cuando todo le esta saliendo mal, es porque ya tiene pensado a quien echarle la culpa.",
    "Si buscas una mano dispuesta a ayudarte, la encontraras al final de tu brazo.",
    "Optimista es aquel que cree poder resolver un atasco de trafico tocando el claxon.",
    "Sonrie es lo segundo mejor que puedes hacer con tus labios",
    "En estos tiempos se necesita mucho ingenio para cometer un pecado original.",
    "Nacemos desnudos, humedos y hambrientos. Despues la cosa empeora.",
    "El tiempo es el mejor maestro, desgraciadamente mata a todos sus estudiantes.",
    "Hay tres tipos de personas: los que saben contar y los que no.",
    "He oido hablar tan bien de ti, que creia que estabas muerto.",
    "El que nace pobre y feo tiene grandes posibilidades de que al crecer se le desarrollen ambas condiciones.",
    "El dinero no trae la felicidad, pero en cuanto el primero se va, la segunda lo sigue.",
    "Lo importante no es ganar sino hacer perder al otro.",
    "El problema de los imparciales es que estan sobornados por las dos partes.",
    "Si no puedes convencerlos, confundelos.",
    "Todos deberiamos creer en algo. Yo creo que tomare otra copa.",
    "Mejor que nos gobiernen las prostitutas porque estamos cansados que nos gobiernen sus hijos.",
    "No te tomes la vida en serio, al fin al cabo no saldras vivo de ella.",
    "Es mejor callar y que piensen que eres idiota a hablar y demostrarlo.",
    "Algunos matrimonios acaban bien, otros duran toda la vida.",
    "Recuerda siempre que eres unico. Exactamente igual que todos los demas.",
    "Cada hombre quiere ser el primer amor de una mujer, cada mujer quiere ser el ultimo amor de un hombre.",
    "Una prostituta es una señora que al desvestirse queda en ropa de trabajo.",
    "¿El pene puede ser masculino o femenino? Si mide mas de 12 cms es pene, pero si mide menos de 12 cms es una pena.",
    "Hay un mundo mejor ¡Pero es muy caro!",
    "La mujer que no tiene suerte con los hombres no sabe la suerte que tiene.",
    "Yo si se lo que es trabajar duro, de verdad, porque lo he visto.",
    "Hay que trabajar ocho horas y dormir ocho horas, pero no las mismas.",
    "Estoy en una situacion tan delicada que si mi mujer se va con otro, yo me voy con ellos.",
    "Lo importante no es saber, sino tener el telefono del que sabe",
    "Yo no sufro de locura. la disfruto a cada minuto.",
    "No importa cuantas veces un hombre casado cambie de trabajo. siempre sigue con la misma jefa.",
    "Todo tiempo pasado fue anterior.",
    "De mucho trabajar no se murio nadie. Pero por las dudas, mejor no arriesgarse.",
    "El azucar no engorda. engorda el que se la toma.",
    "El amor dura lo que dura dura.",
    "No deje para mañana lo que puede evitar definitivamente.",
    "Experiencia, es el nombre que le damos a nuestras metidas de pata",
    "Si algo podemos reconocerle a los reincidentes es que no andan cambiando de ideas.",
    "Solo los genios somos modestos.",
    "Para obtener un prestamo, primero debe probar que no lo necesita.",
    "Huye de las tentaciones, pero despacio, para que puedan alcanzarte.",
    "Cuando un medico se equivoca, lo mejor es echarle tierra al asunto.",
    "Tener la conciencia limpia, solo es sintoma de mala memoria.",
    "La verdad absoluta no existe y esto es absolutamente cierto.",
    "Que cada dia sea un renacer, con nuevas esperanzas",
    "Cuando vayas a decir algo, que tus palabras sean mejores que tu silencio.",
    "Si amas algo, dejalo libre, si regresa a ti, es tuyo, si no regresa, nunca lo fue.",
    "Como no sabian que era imposible, lo hicieron.",
    "Lo importante no es lo que han hecho de nosotros, sino lo que hacemos con lo que han hecho de nosotros.",
    "Que tan largo puede ser un minuto dependera de en que lado de la puerta del baño estas",
    "Siento pasos, siento gente, siento quince y siento veinte",
    "La fuerza es la Ley de la Bestia",
    "Solo los genios somos modestos.",
    "Hay estudiantes que les apena ir al hipodromo y ver que hasta los caballos logran terminar su carrera.",
    "Si el dinero pudiera hablar me diria Adios",
    "Si le molesta el mas alla, pongase mas aca.",
    "Un dia sin sol es como, ya sabes, noche.",
    "Si no tiene nada que hacer, por favor no lo haga aqui.",
    "Se bueno con tus hijos. Ellos elegiran tu residencia.",
    "Morir es como dormir, pero sin levantarse a hacer pis.",
    "Si a la primera no lo haces bien, el paracaidismo no es lo tuyo.",
    "Cualquiera se puede equivocar, inclusive yo.",
    "La psiquiatria es el unico negocio donde el cliente nunca tiene la razon.",
    "Se puede aprender mucho sobre el amor en el cine. si no nos distrae la pelicula",
    "Aclamar es aplaudir con la garganta",
    "El matrimonio es como las libretas de ahorro: de tanto meter y sacar se pierde el interes",
    "Estoy mas desconcertado que Adan el dia de la madre",
    "No solia acabar nada, pero ahora.",
    "Solo los genios somos modestos.",
    "Solo se inventa mediante el recuerdo.",
    "La talla de las estatuas disminuye alejandose de ellas; la de los hombres, aproximandose.",
    "La gente no busca razones para hacer lo que quiere hacer, busca excusas.",
    "La magia es un puente que te permite ir del mundo visible hacia el invisible, y aprender las lecciones de ambos mundos.",
    "Todas las batallas en la vida sirven para enseñarnos algo, inclusive aquellas que perdemos.",
    "Escoger un camino significa abandonar otros.",
    "Las conductas, como las enfermedades, se contagian de unos a otros.",
    "El que no aplique nuevos remedios debe esperar nuevos males, porque el tiempo es el maximo innovador.",
    "Cuando el peligro parece ligero, deja de ser ligero.",
    "Vengandose, uno se iguala a su enemigo; perdonandolo, se muestra superior a el.",
    "El requisito del exito es la prontitud en las decisiones.",
    "La antigüedad del tiempo es la juventud del mundo.",
    "La discrecion en el habla es mas que la elocuencia.",
    "Nada induce al hombre a sospechar mucho como el saber poco.",
    "El tiempo es el angel del hombre.",
    "Solo la fantasia permanece siempre joven, lo que no ha ocurrido jamas no envejece nunca.",
    "No es la carne y la sangre, sino el corazon, lo que nos hace padres e hijos.",
    "Si quieres conocerte, observa la conducta de los demas.",
    "Si quieres comprender a los demas, mira en tu propio corazon.",
    "No existe la casualidad, y lo que se nos presenta como azar surge de las fuentes mas profundas.",
    "La historia es un incesante volver a empezar.",
    "El silencio es la virtud de los locos",
    "En materia de gobierno todo cambio es sospechoso, aunque sea para mejorar.",
    "La verdad es hija del tiempo, no de la autoridad.",
    "Vieja madera para arder, viejo vino para beber, viejos amigos en quien confiar, y viejos autores para leer.",
    "Es muy dificil hacer compatible la politica con la moral.",
    "Si comienza uno con certezas, terminara con dudas; mas si acepta empezar con dudas, llegara a terminar con certezas.",
    "Quien no quiere pensar es un fanatico; quien no puede pensar es un idiota; quien no osa pensar es un cobarde.",
    "Es bueno adquirir poco a poco la conformidad de no entender nada.",
    "Cada vez que cometo un error me parece descubrir una verdad que no conocia.",
    "No lo que hicimos ayer, sino lo que vamos a hacer mañana juntos, no reune en Estado.",
    "El pensamiento es la unica cosa del Universo de la que no se puede negar su existencia: negar es pensar.",
    "El mayor crimen esta ahora no en los que matan, sino en los que no matan pero dejan matar.",
    "La vida cobra sentido cuando se hace de ella una aspiracion a no renunciar a nada.",
    "Evitemos suplantar con nuestro mundo el de los demas.",
    "Todo es resultado de un esfuerzo. Solo se aguanta una civilizacion si muchos aportan su colaboracion al esfuerzo.",
    "El malvado descansa algunas veces; el necio, jamas.",
    "La vida es una extraña mezcla de azar, destino y caracter.",
    "Donde la fuerza oprime, la ley se quiebra.",
    "La primera condicion para la inmortalidad es la muerte.",
    "Cuando no sopla el viento, incluso la veleta tiene caracter.",
    "El que busca el cielo en la Tierra se ha dormido en clase de geografia.",
    "Todas las cosas son imposibles, mientras lo parecen.",
    "El error es un arma que acaba siempre por dispararse contra el que la emplea.",
    "Las fuerzas que se asocian para el bien no se suman, se multiplican.",
    "Cuando la culpa es de todos, la culpa no es de nadie.",
    "Un hombre aislado se siente debil, y lo es.",
    "La pasion para el hombre es un torrente; para la mujer, un abismo.",
    "No existe una mejor prueba de progreso de una civilizacion que la del progreso de la cooperacion.",
    "Silenciar una version es una peculiar forma de hacer mal.",
    "Has de saber mas que los demas, si puedes, pero no lo digas.",
    "Lo importante no es escuchar lo que se dice, sino averiguar lo que se piensa.",
    "En lo pasado esta la historia del futuro.",
    "Hay que unirse, no para estar juntos, sino para hacer algo juntos.",
    "Le quiero como a un hermano. Como Cain a Abel.",
    "No te metas con la masturbacion. Es hacer el amor con alguien a quien yo quiero.",
    "Mi cerebro es mi segundo organo favorito.",
    "No creo en una vida posterior, pero por si acaso me he cambiado de ropa interior.",
    "La ultima vez que estuve dentro de una mujer fue cuando visite la Estatua de la Libertad.",
    "No tengo nada en contra de la ciencia. Yo, entre el aire acondicionado y el Papa, escojo el aire.",
    "La vocacion del politico de carrera es hacer de cada solucion un problema.",
    "Me interesa el futuro porque es el sitio donde voy a pasar el resto de mi vida.",
    "No es que tenga miedo de morirme, es tan solo que no quiero estar alli cuando suceda.",
    "El que busca la verdad corre el riesgo de encontrarla.",
    "Ser una mujer es una tarea terriblemente dificil, ya que consiste principalmente en tratar con hombres.",
    "A las personas se las conoce por sus palabras.",
    "Si vieramos realmente el Universo, tal vez lo entenderiamos.",
    "Uno no es lo que es por lo que escribe, sino por lo que ha leido.",
    "Si de algo soy rico es de perplejidades y no de certezas.",
    "Antes las distancias eran mayores porque el espacio se mide por el tiempo.",
    "La historia universal es la de un solo hombre.",
    "No nos une el amor, nos une el espanto.",
    "La duda es uno de los nombres de la inteligencia.",
    "Siempre imagine que el Paraiso seria algun tipo de biblioteca.",
    "Hay que tener cuidado al elegir a los enemigos porque uno termina pareciendose a ellos",
    "El honor consiste en hacer hermoso aquello que uno esta obligado a realizar.",
    "Los años enseñan muchas cosas que los dias jamas llegan a conocer.",
    "Emplea el lenguaje que quieras y nunca podras expresar sino lo que eres.",
    "Un heroe no es mas valiente que un hombre normal, pero es valiente cinco minutos mas.",
    "Grabad esto en vuestro corazon: cada dia es el mejor del año.",
    "La sociedad es en todos los sitios una conspiracion contra la personalidad de cada uno de sus miembros.",
    "unicamente la obediencia tiene derecho al mando.",
    "Los astutos vencen siempre en el primer momento, y suelen ser vencidos antes del fin.",
    "Todo hombre no vive mas que por lo que espera.",
    "Cuando los ricos hacen la guerra son los pobres los que mueren.",
    "La libertad es lo que haces con lo que te han hecho.", 
    "La arena del desierto es para el viajero fatigado lo mismo que la conversacion incesante para el amante del silencio.",
    "La contemplacion es un lujo, mientras que la accion es una necesidad.",
    "El presente solo se forma del pasado, y lo que se encuentra en el efecto estaba ya en la causa.",
    "Los conceptos estan incluidos en las palabras.",
    "El castigo del embustero es no ser creido, aun cuando diga la verdad.",
    "El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.",
    "La historia cuenta lo que sucedio; la poesia lo que debio suceder.",
    "El instante es la continuidad del tiempo, pues une el tiempo pasado con el tiempo futuro.",
    "Es de importancia para quien desee alcanzar una certeza en su investigacion, el saber dudar a tiempo.",
    "La multitud obedece mas a la necesidad que a la razon.",
    "Los grandes conocimientos engendran las grandes dudas.",
    "No basta decir solamente la verdad, mas conviene mostrar la causa de la falsedad.",
    "El hombre nada puede aprender sino en virtud de lo que ya sabe.",
    "Nunca se alcanza la verdad total, ni nunca se esta totalmente alejado de ella.",
    "Todo acto forzoso se vuelve desagradable.",
    "El miedo es un sufrimiento que produce la espera de un mal.",
    "No se puede ser y no ser algo al mismo tiempo y bajo el mismo aspecto.",
    "Enseñar no es una funcion vital, porque no tiene el fin en si misma; la funcion vital es aprender.",
    "El tiempo es la medida del movimiento entre dos instantes.",
    "Es preciso preferir la soberania de la ley a la de uno de los ciudadanos.",
    "Las cosas se llaman equivocas cuando solo tienen de comun el nombre.", 
    "La primera tarea de la educacion es agitar la vida, pero dejarla libre para que se desarrolle.",
    "Debo, puedo, luego quiero.",
    "Los bribones y los necios son plantas de cualquier terreno.",
    "Solo en un mundo de hombres sinceros es posible la union.",
    "El presente es la viviente suma total del pasado.",
    "Hablar es el arte de sofocar e interrumpir el pensamiento.",
    "Para disipar una duda, cualquiera que fuera, se necesita una accion.",
    "De nada sirve al hombre lamentarse de los tiempos en que vive, lo unico bueno que puede hacer es intentar mejorarlos.",
    "Es un error esencial considerar la violencia como una fuerza.",
    "El conocimiento nos hace responsables.",
    "El valor es hijo de la prudencia, no de la temeridad.",
    "Hay que evitar el combate. Hay triunfos que empobrecen al vencido, pero no enriquecen al vencedor.",
    "No es tan dañino oir lo superficial como dejar de escuchar lo necesario.",
    "Los malos habitos es mas facil romperlos que enmendarlos.",
    "Una prensa libre puede ser buena o mala, pero sin libertad, la prensa nunca sera otra cosa que mala.",
    "Es muy facil obtener fama, pero es muy dificil merecerla.",
    "El otoño es una segunda primavera, donde cada hoja es una flor.",
    "Si el hombre fracasa en conciliar la justicia y la libertad, fracasa en todo.",
    "La capacidad de un hombre es limitada y debe ser espoleada por la provocacion.",
    "Un hombre sin etica es una bestia salvaje soltada a este mundo.",
    "Nada graba tan fijamente en nuestra memoria alguna cosa como el deseo de olvidarla.",
    "Toda persona honrada prefiere perder su honor a perder su conciencia.",
    "Saber mucho da ocasion de dudar mas.",
    "El que no este seguro de su memoria debe abstenerse de mentir.",
    "Quien se eleva demasiado cerca del sol con alas de oro las funde.",
    "El hombre cauto jamas deplora el mal presente, lo emplea en prevenir las aflicciones futuras.", 
    "La memoria es el centinela del cerebro.",
    "El destino es el que baraja las cartas, pero nosotros somos los que jugamos.",
    "Las medidas templadas, que equivalen a remedios prudentes, son hartamente nocivas cuando el mal es violento.",
    "Los cobardes mueren muchas veces antes de su verdadera muerte,  los valientes gustan la muerte solo una vez.",
    "La mujer es un manjar digno de los dioses; pero a veces lo guisa el diablo.",
    "Si el dinero va delante, todos los caminos se abren.",
    "La verdadera sabiduria esta en reconocer la propia ignorancia.",
    "Solo hay un bien, el conocimiento, solo hay un mal, la ignorancia.",
    "Cada uno de nosotros solo sera justo en la medida en que haga lo que le corresponde.",
    "Azar es una palabra vacia de sentido, nada puede existir sin causa.",
    "La pasion de dominar es la mas terrible de todas las enfermedades del espiritu humano.",
    "Proclamo en voz alta la libertad de pensamiento y muera el que no piense como yo.",
    "Lo que llamamos casualidad no es ni puede ser sino la causa ignorada de un efecto desconocido.",
    "Quienes creen que el dinero lo hace todo, terminan haciendo todo por dinero.",
    "A los vivos se les debe respeto, a los muertos nada mas que la verdad.",
    "Es un riesgo tener razon cuando el Gobierno esta equivocado.",
    "La historia no es mas que una lista de crimenes y desgracias.",
    "Quien no tiene toda la inteligencia de su edad, tiene toda su desgracia.",
    "Las falsedades no solo se oponen a la verdad, sino que a menudo se contradicen entre si.",
    "Culto es aquel que sabe donde encontrar lo que no sabe.",
    "El corazon en paz ve una fiesta en todas las aldeas.",
    "Cuando hables, procura que tus palabras sean mejores que el silencio.",
    "Divide las dificultades que examinas en tantas partes como sea posible para su mejor solucion.",
    "Dos cosas contribuyen a avanzar, ir mas deprisa que los otros o ir por el buen camino.",
    "No basta tener buen ingenio; lo principal es aplicarlo bien.",
    "Para investigar la verdad es preciso dudar, en cuanto sea posible, de todas las cosas.",
    "Lo poco que he aprendido carece de valor, comparado con lo que ignoro y no desespero en aprender.",
    "Para mejorar nuestro conocimiento debemos aprender menos y contemplar mas.",
    "Abrigamos muchos prejuicios si no dudamos, alguna vez, de todo en lo que vemos la menor sospecha de incertidumbre.",
    "Es prudente no fiarse por entero de quienes nos han engañado antes.",
    "La primera maxima de todo ciudadano ha de ser la de obedecer las leyes de su pais.",
    "Inspiracion y genio son casi la misma cosa.",
    "Produce una inmensa tristeza pensar que la naturaleza habla mientras el genero humano no escucha.",
    "Es extraña la ligereza con que los malvados creen que todo les saldra bien.",
    "El amor abre el parentesis, el matrimonio lo cierra.",
    "La primera igualdad es la equidad.",
    "Todo numero es cero ante el infinito.",
    "A nadie le faltan fuerzas; lo que a muchisimos les falta es voluntad.",
    "Las inteligencias poco capaces se interesan en lo extraordinario, las inteligencias poderosas, en las cosas ordinarias.",
    "La musica expresa aquello que no puede decirse con palabras pero no puede permanecer en silencio.",
    "La pena de muerte es un signo peculiar de la barbarie.",
    "El exito no se logra solo con cualidades especiales, es sobre todo un trabajo de constancia, de metodo y de organizacion.",
    "El tiempo es oro.",
    "Un amigo es aquel que adivina siempre cuando se le necesita.",
    "He construido castillos en el aire tan hermosos que me conformo con las ruinas.",
    "La diligencia en escuchar es el mas breve camino hacia la ciencia.",
    "Nada es mas facil ni tan util como escuchar mucho.",
    "Lo comprado al precio de muchos ruegos es caro.",
    "La incertidumbre es una margarita cuyos petalos no se terminan jamas de deshojar.",
    "La politica saca a flote lo peor del ser humano.",
    "No hay un solo error que no haya tenido sus seguidores.",
    "En la vida no hay premios ni castigos, sino consecuencias.",
    "La habilidad y la constancia son las armas de la debilidad.",
    "No perdais una hora, porque no estais seguros de un minuto.",
    "El hombre es un animal fabricante de utensilios.",
    "O caminamos todos juntos hacia la paz, o nunca la encontraremos.",
    "La peor decision es la indecision.",
    "Las puertas de la sabiduria nunca estan cerradas.",
    "Dime y lo olvido, enseñame y lo recuerdo, involucrame y lo aprendo.",
    "Cuida de los pequeños gastos; un pequeño agujero hunde un barco.",
    "Incluso la paz se puede comprar a un precio demasiado alto.",
    "Nunca hubo una buena guerra, o una mala paz.",
    "El sabio consigue mas ventajas por sus enemigos que por sus amigos.",
    "La necesidad nunca consiguio un buen acuerdo.",
    "Verdad es lo que la mayoria ve como verdad, pero la mayoria tambien puede cambiar de opinion a lo largo de la historia.",
    "El lenguaje y la imaginacion no pueden ser aprisionados.",
    "La lengua es el mas mortifero de los instrumentos sin punta.",
    "Para todo problema humano hay siempre una solucion facil, clara, plausible y equivocada.",
    "Confianza es el sentimiento de poder creer a una persona, incluso cuando sabemos que mentiriamos en su lugar.",
    "Una derrota peleada vale mas que una victoria casual.",
    "La libertad es un lujo que no todos pueden permitirse.",
    "Con las leyes pasa como con las salchichas, es mejor no ver como se hacen",
    "En el punto donde se detiene la ciencia, empieza la imaginacion.",
    "Mientras haya libros no existe el pasado.",
    "Mas vale el peor concierto que no el divorcio mejor.",
    "La verdad anda sobre la mentira como el aceite sobre el agua.",
    "En las cortesias antes se ha de pecar por carta de mas que de menos.",
    "La falsedad tiene alas y vuela, y la verdad la sigue arrastrandose.", 
    "Las sentencias cortas se derivan de una gran experiencia.",
    "Si la ayuda y la salvacion han de llegar solo puede ser a traves de los niños.",
    "Confia en el tiempo, que suele dar dulces salidas a muchas amargas dificultades.",
    "Los males que no tienen fuerza para acabar la vida, no han de tenerla para acabar la paciencia.",
    "El ver mucho y leer mucho aviva los ingenios de los hombres.",
    "Pocas o ninguna vez se cumple con la ambicion que no sea con daño de tercero.",
    "Un caballero se avergüenza de que sus palabras sean mejores que sus hechos.",
    "Contra el callar no hay castigo ni respuesta.",
    "Una cosa es continuar la historia y otra repetirla.",
    "Mas se unen los hombres para compartir un mismo odio que un mismo amor.",
    "El enemigo solo empieza a ser temible cuando empieza a tener razon.",
    "Lo peor que hacen los malos es obligarnos a dudar de los buenos.",
    "Es mas facil ser genial que tener sentido comun.",
    "El amor es como Don Quijote, cuando recobra el juicio es que esta para morir.",
    "El unico egoismo aceptable es el de procurar que todos esten bien para estar uno mejor.",
    "Acepto el caos, pero no estoy seguro de que el caos me acepte a mi.",
    "Actua siempre como si fuera imposible fracasar.",
    "Seguir un solo camino es retroceder."
	]

  m5.say(random.choice(fact_core))

fact_core.commands = ['frases']
fact_core.priority = 'low'

if __name__ == '__main__':
   print __doc__.strip()
